/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("tracker.kotlin-application-conventions")
    kotlin("plugin.serialization") version "1.9.10"
}

dependencies {
    implementation("io.github.cdimascio:dotenv-java:3.0.0")
    implementation("org.apache.commons:commons-text")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
    implementation(project(":kafka"))
}

application {
    // Define the main class for the application.
    mainClass.set("example.AppKt")
}
